Update packaging.yml

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -50,9 +50,14 @@ jobs:
         [ -d $FIRMWARE_PATH ] || mkdir -p $FIRMWARE_PATH
         #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
         #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/download/OpenWrt-NewK" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
-        wget -q -P $FIRMWARE_PATH https://productionresultssa4.blob.core.windows.net/actions-results/574b423d-4ef3-4ee4-b0c0-24fb1a35c0d5/workflow-job-run-c7632941-855f-5494-8ed9-7e16b6900374/artifacts/ecad907917b9d14f0ac758540621ccccbb8d56320c5bfc01a5020325b0ec8313.zip?rscd=attachment%3B+filename%3D%2203.15_armsr_armv8.zip%22&se=2025-03-15T09%3A01%3A23Z&sig=KXUayqs3j3hh0t1WScwAy5EDRfLR6W2DS8PQvXUw%2BmE%3D&ske=2025-03-15T17%3A05%3A23Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-03-15T05%3A05%3A23Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-03-15T08%3A51%3A18Z&sv=2025-01-05
+        wget -q -P $FIRMWARE_PATH https://productionresultssa4.blob.core.windows.net/actions-results/574b423d-4ef3-4ee4-b0c0-24fb1a35c0d5/workflow-job-run-c7632941-855f-5494-8ed9-7e16b6900374/artifacts/*.*rootfs.tar.gz
+        if [ -f "$FIRMWARE_PATH/rootfs.tar.gz" ]; then
         echo "status=success" >> $GITHUB_OUTPUT
-
+        else
+        echo "status=failure" >> $GITHUB_OUTPUT
+        exit 1
+        fi       
+        
     - name: Package Armvirt as OpenWrt
       if: steps.download.outputs.status == 'success'
       uses: unifreq/openwrt_packit@master
